# Generated by Django 3.1 on 2020-09-01 18:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200831_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='About',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='About Author'),
            preserve_default=False,
        ),
    ]
