# Generated by Django 3.1 on 2020-09-01 18:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='About',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
