# Generated by Django 3.1 on 2020-09-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200901_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
