# Generated by Django 3.1 on 2020-09-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
