# Generated by Django 3.1 on 2020-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200917_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metadesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='metatitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
