# Generated by Django 3.1 on 2020-10-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20201026_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
