# Generated by Django 3.1 on 2020-09-17 17:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='static_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('metatitle', models.CharField(blank=True, max_length=100, null=True)),
                ('metadesc', models.CharField(blank=True, max_length=250, null=True)),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
