# Generated by Django 3.1 on 2020-09-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static_page',
            name='name',
        ),
    ]
