# Generated by Django 3.1 on 2020-09-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_static_page_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='static_page',
        ),
    ]
