# Generated by Django 3.1 on 2020-09-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category_page',
        ),
    ]
